### ISSUE TITLE
Update basis-size upon changing to a truncated basis

### ISSUE THREAD

**Issue by halvarsu** [Schoyen/quantum-systems#20]
When changing to a smaller basis, variables such as basis size `l` does not update in `system` (see below). I don't know if this is outside the intended use of the system-class, but it would be useful when using a truncated basis with SINC-DVR. 

![image](https://user-images.githubusercontent.com/16295619/72455235-b77fa380-37c2-11ea-9f22-275a1b884863.png)

**Comment by Schoyen** [comment]
Great catch! The number of basis functions `l` should definitely reflect the size of the matrix elements.

**Comment by halvarsu** [comment]
What is the reasoning behind calling `check_axis_lengths`? https://github.com/Schoyen/quantum-systems/blob/0d8c797f469244055a5b4cfd6f4a9491343c336d/quantum_systems/system.py#L94 

If it is to ensure that spin-doubling should only occur once, could a solution be a flag `spin_orbitals = True/False` which has to be `False` for `change_to_spin_orbital_basis` to run, while at the same time letting `l` be the number of 'whatever-orbitals'? Or does this put to much responsibility on the user, since the user would have to specify whenever a restricted system was being setup (assuming `spin_orbitals = True` was the default, it wouldn't have to be)

**Comment by Schoyen** [comment]
Yeah, it was included to make sure that a system is not spin-doubled more than once (it can be questioned how smooth it is to crash instead of give a warning...). Your solution to use a flag is in my opinion equally good. This flag can be determined based on the value of the keyword argument `add_spin` wherever this occurs.

**Comment by halvarsu** [comment]
Thats a good idea, then a warning can be raised whenever the add_spin-flag doesn't correspond to the spin_orbital-flag.  

Should there be a way to reduce the size of the system, i.e. remove spin doubling? Is there a case where this is relevant? I can imagine it being done by manually setting the matrix-elements and system size, but should one then also be able to set the spin-orbital-flag to False.

**Comment by Schoyen** [comment]
Hmm, the reverse can be achieved by using the spin-dependent slices. Incidentally, these slices (`o_a`, `o_b`, `v_a`, `v_b`) only needs to be created in case of `spin_orbital=True`.
