### ISSUE TITLE
Force even number of basis functions?

### ISSUE THREAD

**Issue by halvarsu** [Schoyen/quantum-systems#26]
In my transition from `CustomSystem` to `QuantumSystem`, I realised that the latter forces `l % 2 == 0` but the former did not. Shouldn't it be possible for systems to have an odd number of basis functions?

https://github.com/Schoyen/quantum-systems/blob/0d8c797f469244055a5b4cfd6f4a9491343c336d/quantum_systems/system.py#L55

**Comment by Schoyen** [comment]
Huh, this is related to #20, where we use `l` as the number of spin-orbitals and a restricted system must use `l // 2`. Then `l` should always be an even number. However, it sounds like it is long overdue to just let `l` be the number of "whatever-orbitals" and let it reflect the number of basis elements.
