### ISSUE TITLE
misleading function name

### ISSUE THREAD

**Issue by halvarsu** [Schoyen/quantum-systems#30]
This function https://github.com/Schoyen/quantum-systems/blob/3499369a0cf42cdc42157126081118b75a4f66b8/quantum_systems/spatial_orbital_system.py#L52
does not change the system itself. It just creates a copy, which can be a bit misleading. Maybe it should be renamed? Either that, or be made static?

**Comment by Schoyen** [comment]
Well, it doesn't quite create a copy as the function "destroys" the current `SpatialOrbitalSystem`. However, I can agree that the name doesn't quite fit; `SpatialOrbitalSystem` doesn't get so much changed as it gets replaced. Any suggestions? 😀

**Comment by halvarsu** [comment]
See suggested fix based on our discussion in #31 :)
