### ISSUE TITLE
basis_set creates bra_spf

### ISSUE THREAD

**Issue by halvarsu** [Schoyen/quantum-systems#42]
When constructing a basis_set with `spf` which is not `None`, a bra_spf is generated due to this property getter, https://github.com/Schoyen/quantum-systems/blob/161c38b0bf1031729134d953a4f8122ba2e47948/quantum_systems/basis_set.py#L133.

However, this forces us to also supply a `C_tilde` when changing basis, due to line 259 in `basis_set.py`, in the method `_change_basis_spf, or else one ends up with an assertion error such as seen below. 

How to fix: I propose to either change the getter of bra_spf, or letting `_change_basis_spf` use C.T.conj() if C_tilde is not supplied.
```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-137-6c4c90815204> in <module>
      6 from coupled_cluster import OACCD
      7 
----> 8 system_g = GeneralOrbitalSystem(4, basis_prime)
      9 # OACCD = OACCD(system_g)
     10 basis_set.bra_spf.shape

~/uio/master/modules/quantum-systems/quantum_systems/general_orbital_system.py in __init__(self, n, basis_set, anti_symmetrize, **kwargs)
     28         if not basis_set.includes_spin:
     29 
---> 30             basis_set = basis_set.change_to_general_orbital_basis(
     31                 anti_symmetrize=anti_symmetrize
     32             )

~/uio/master/modules/quantum-systems/quantum_systems/basis_set.py in change_to_general_orbital_basis(self, anti_symmetrize)
    430             # potentially construct the dual state.
    431             if not self._bra_spf is None:
--> 432                 self.bra_spf = self.add_spin_bra_spf(self._bra_spf, self.np)
    433 
    434         return self

~/uio/master/modules/quantum-systems/quantum_systems/basis_set.py in bra_spf(self, bra_spf)
    138     def bra_spf(self, bra_spf):
    139         if not bra_spf is None:
--> 140             assert bra_spf.shape[0] == self.l
    141             assert len((*bra_spf.shape[1:],)) == self.dim
    142 

AssertionError:
```

**Comment by Schoyen** [comment]
Great catch! The logic behind the `bra_spf`-getter is a mess, however I think the getter should stay as it is. This allows all downstream code to use `bra_spf` without checking if it exists or not. The solution to set `C_tilde = C.T.conj()` if `C_tilde == None` is, I believe, the simplest solution.
